/**
 * Catalog data-access layer.
 *
 * The UI never reads raw JSON directly — it goes through these functions,
 * which return the typed `Product` / `Collection` / `Look` / `Mood` objects
 * defined in `types/catalog.ts`. To migrate to Shopify, re-implement this
 * module against the Storefront API; the components stay unchanged.
 *
 * Datasets are generated by `scripts/build-dataset.mjs` from public reference
 * data scraped with permission (polite crawl, robots.txt respected).
 */
import productsData from "@/data/products.json";
import collectionsData from "@/data/collections.json";
import looksData from "@/data/looks.json";
import siteData from "@/data/site.json";
import merchandisingData from "@/config/merchandising.json";

import type {
  Collection,
  Look,
  Mood,
  Product,
  ProductRecommendation,
  RecommendationType,
} from "@/types/catalog";

/* ------------------------------------------------------------------ */
/* Types for queries                                                   */
/* ------------------------------------------------------------------ */

export interface ProductFilters {
  /** Collection handle (category, edit or sale), e.g. "linen". */
  collection?: string;
  /** Any-of collection handles (used for mood/occasion pages). OR within. */
  collections?: string[];
  /** Category names. Multi-select: OR within. */
  category?: string | string[];
  /** Color-family names, e.g. "Bronzed Dune". */
  colorFamily?: string | string[];
  /** Min price in cents. */
  minPrice?: number;
  /** Max price in cents. */
  maxPrice?: number;
  /** Only in-stock products. */
  available?: boolean;
  /** Only discounted products. */
  onSale?: boolean;
  /** Free-text query (title/category/material/color family/tags). */
  query?: string;
}

export type SortOption =
  | "featured"
  | "newest"
  | "price-asc"
  | "price-desc"
  | "name-asc"
  | "name-desc";

export interface ProductsPage {
  products: Product[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

const asArray = (v: string | string[] | undefined): string[] =>
  v == null ? [] : Array.isArray(v) ? v : [v];

/* ------------------------------------------------------------------ */
/* Raw data                                                            */
/* ------------------------------------------------------------------ */

export const ALL_PRODUCTS = productsData as Product[];
export const ALL_COLLECTIONS = collectionsData as Collection[];
export const ALL_LOOKS = looksData as Look[];
export const SITE = siteData;
export const MERCHANDISING = merchandisingData;

const productByHandle = new Map(ALL_PRODUCTS.map((p) => [p.handle, p]));
const collectionByHandle = new Map(
  ALL_COLLECTIONS.map((c) => [c.handle, c]),
);
const lookByHandle = new Map(ALL_LOOKS.map((l) => [l.handle, l]));

export const MOODS: Mood[] = merchandisingData.moods ?? [];

/** All product categories with real counts (used by nav + filters). */
export const CATEGORIES: { name: string; count: number; handle: string }[] = (
  () => {
    const map = new Map<string, number>();
    for (const p of ALL_PRODUCTS) {
      const c = p.category || "Other";
      map.set(c, (map.get(c) ?? 0) + 1);
    }
    return [...map.entries()]
      .map(([name, count]) => ({
        name,
        count,
        handle: slugify(name),
      }))
      .sort((a, b) => b.count - a.count);
  }
)();

/** Editorial edits (collections of type "edit"), ordered for nav. */
export const EDITS: Collection[] = ALL_COLLECTIONS.filter(
  (c) => c.type === "edit",
).sort((a, b) => (a.sort ?? 99) - (b.sort ?? 99));

function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");
}

/* ------------------------------------------------------------------ */
/* Lookups                                                             */
/* ------------------------------------------------------------------ */

export function getProduct(handle: string): Product | undefined {
  return productByHandle.get(handle);
}

export function getCollection(handle: string): Collection | undefined {
  return collectionByHandle.get(handle);
}

export function getLook(handle: string): Look | undefined {
  return lookByHandle.get(handle);
}

export function getProducts(handles: string[]): Product[] {
  return handles
    .map((h) => productByHandle.get(h))
    .filter((p): p is Product => Boolean(p));
}

/** Products in a collection (in collection order). */
export function collectionProducts(
  collection: Collection | undefined,
): Product[] {
  if (!collection) return [];
  return getProducts(collection.productHandles ?? []);
}

/** Products in a mood (union of its real collection membership). */
export function moodProducts(mood: Mood): Product[] {
  const colHandles = new Set(mood.categories);
  return ALL_PRODUCTS.filter((p) =>
    (p.collections ?? []).some((c) => colHandles.has(c)),
  );
}

/* ------------------------------------------------------------------ */
/* Filtering + sorting                                                 */
/* ------------------------------------------------------------------ */

export function filterProducts(
  filters: ProductFilters = {},
  sort: SortOption = "featured",
  opts: { page?: number; pageSize?: number } = {},
): ProductsPage {
  const page = opts.page ?? 1;
  const pageSize = opts.pageSize ?? 24;

  let result = ALL_PRODUCTS;

  if (filters.collection) {
    const col = collectionByHandle.get(filters.collection);
    if (col) {
      const set = new Set(col.productHandles ?? []);
      result = result.filter((p) => set.has(p.handle));
    }
  }

  if (filters.collections && filters.collections.length > 0) {
    const sets = filters.collections
      .map((h) => collectionByHandle.get(h)?.productHandles ?? [])
      .flat();
    const allowed = new Set(sets);
    result = result.filter((p) => allowed.has(p.handle));
  }

  const categories = asArray(filters.category).map((c) => c.toLowerCase());
  if (categories.length > 0) {
    const set = new Set(categories);
    result = result.filter((p) => set.has(p.category.toLowerCase()));
  }

  const colorFamilies = asArray(filters.colorFamily).map((c) =>
    c.toLowerCase(),
  );
  if (colorFamilies.length > 0) {
    const set = new Set(colorFamilies);
    result = result.filter(
      (p) => p.colorFamily && set.has(p.colorFamily.toLowerCase()),
    );
  }

  if (filters.minPrice != null) {
    result = result.filter((p) => p.price.amount >= filters.minPrice!);
  }
  if (filters.maxPrice != null) {
    result = result.filter((p) => p.price.amount <= filters.maxPrice!);
  }
  if (filters.available) {
    result = result.filter((p) => p.availableForSale);
  }
  if (filters.onSale) {
    result = result.filter((p) => p.compareAtPrice != null);
  }
  if (filters.query) {
    const q = filters.query.toLowerCase();
    result = result.filter((p) =>
      [p.title, p.category, p.material, p.colorFamily, ...p.tags]
        .filter(Boolean)
        .join(" ")
        .toLowerCase()
        .includes(q),
    );
  }

  result = sortProducts(result, sort);

  const total = result.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const start = (page - 1) * pageSize;
  return {
    products: result.slice(start, start + pageSize),
    total,
    page,
    pageSize,
    totalPages,
  };
}

export function sortProducts(products: Product[], sort: SortOption): Product[] {
  const arr = [...products];
  switch (sort) {
    case "price-asc":
      return arr.sort((a, b) => a.price.amount - b.price.amount);
    case "price-desc":
      return arr.sort((a, b) => b.price.amount - a.price.amount);
    case "name-asc":
      return arr.sort((a, b) => a.title.localeCompare(b.title));
    case "name-desc":
      return arr.sort((a, b) => b.title.localeCompare(a.title));
    case "newest":
      return arr.sort(
        (a, b) =>
          Number(b.tags.includes("new")) - Number(a.tags.includes("new")),
      );
    case "featured":
    default:
      return arr.sort(
        (a, b) =>
          Number(b.tags.includes("best-seller")) -
          Number(a.tags.includes("best-seller")),
      );
  }
}

/* ------------------------------------------------------------------ */
/* Aggregations                                                        */
/* ------------------------------------------------------------------ */

export interface FilterOptions {
  categories: { name: string; count: number }[];
  colorFamilies: { name: string; count: number }[];
  priceBounds: { min: number; max: number };
  total: number;
  inStock: number;
  onSale: number;
}

export function getFilterOptions(context?: {
  collection?: string;
}): FilterOptions {
  let pool = ALL_PRODUCTS;
  if (context?.collection) {
    const col = collectionByHandle.get(context.collection);
    if (col) {
      const set = new Set(col.productHandles ?? []);
      pool = pool.filter((p) => set.has(p.handle));
    }
  }

  const categoryMap = new Map<string, number>();
  const colorMap = new Map<string, number>();
  let min = Infinity;
  let max = 0;
  let inStock = 0;
  let onSale = 0;
  for (const p of pool) {
    const c = p.category || "Other";
    categoryMap.set(c, (categoryMap.get(c) ?? 0) + 1);
    if (p.colorFamily)
      colorMap.set(
        p.colorFamily,
        (colorMap.get(p.colorFamily) ?? 0) + 1,
      );
    if (p.price.amount > 0) {
      min = Math.min(min, p.price.amount);
      max = Math.max(max, p.price.amount);
    }
    if (p.availableForSale) inStock++;
    if (p.compareAtPrice) onSale++;
  }

  return {
    categories: [...categoryMap.entries()]
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count),
    colorFamilies: [...colorMap.entries()]
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count),
    priceBounds: { min: min === Infinity ? 0 : min, max },
    total: pool.length,
    inStock,
    onSale,
  };
}

/* ------------------------------------------------------------------ */
/* Merchandising                                                       */
/* ------------------------------------------------------------------ */

export function bestSellers(limit = 8): Product[] {
  const tagged = ALL_PRODUCTS.filter((p) => p.tags.includes("best-seller"));
  if (tagged.length >= limit) return tagged.slice(0, limit);
  const inStock = ALL_PRODUCTS.filter((p) => p.availableForSale);
  return [...tagged, ...inStock].slice(0, limit);
}

export function newArrivals(limit = 8): Product[] {
  const tagged = ALL_PRODUCTS.filter((p) => p.tags.includes("new"));
  if (tagged.length >= limit) return tagged.slice(0, limit);
  return [...tagged, ...bestSellers(limit * 3)].slice(0, limit);
}

export function saleProducts(limit = 8): Product[] {
  return ALL_PRODUCTS.filter((p) => p.compareAtPrice != null)
    .sort((a, b) => {
      const da = a.compareAtPrice!.amount - a.price.amount;
      const db = b.compareAtPrice!.amount - b.price.amount;
      return db - da;
    })
    .slice(0, limit);
}

export function collectionColorFamilies(
  collection: Collection | undefined,
): { name: string; count: number }[] {
  const map = new Map<string, number>();
  for (const p of collectionProducts(collection)) {
    if (p.colorFamily)
      map.set(p.colorFamily, (map.get(p.colorFamily) ?? 0) + 1);
  }
  return [...map.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);
}

/* ------------------------------------------------------------------ */
/* Recommendations                                                     */
/* ------------------------------------------------------------------ */

export function getRecommendations(
  productHandle: string,
  types: RecommendationType[] = [
    "complete-the-look",
    "related",
    "best-sellers",
  ],
): ProductRecommendation[] {
  const product = productByHandle.get(productHandle);
  const recs: ProductRecommendation[] = [];
  const seen = new Set<string>([productHandle]);

  const add = (type: RecommendationType, products: Product[], max: number) => {
    for (const p of products) {
      if (seen.has(p.handle)) continue;
      seen.add(p.handle);
      recs.push({ type, productId: p.handle });
      if (recs.filter((r) => r.type === type).length >= max) break;
    }
  };

  if (product) {
    if (types.includes("complete-the-look")) {
      // Real merchandising: same coordinating color family (the brand sells
      // matching separates — e.g. Bronzed Dune poncho + trousers + mini skirt).
      const sameFamily = ALL_PRODUCTS.filter(
        (p) =>
          p.colorFamily &&
          product.colorFamily &&
          p.colorFamily === product.colorFamily &&
          p.handle !== product.handle,
      );
      add("complete-the-look", sameFamily, 4);

      // Fallback: shared edit/collection membership.
      if (!recs.some((r) => r.type === "complete-the-look")) {
        const shared = new Map<string, number>();
        for (const colHandle of product.collections) {
          for (const h of collectionByHandle.get(colHandle)?.productHandles ??
            []) {
            shared.set(h, (shared.get(h) ?? 0) + 1);
          }
        }
        const mates = [...shared.entries()]
          .filter(([h]) => h !== productHandle)
          .sort((a, b) => b[1] - a[1])
          .slice(0, 8)
          .map(([h]) => productByHandle.get(h))
          .filter((p): p is Product => Boolean(p));
        add("complete-the-look", mates, 4);
      }
    }

    if (types.includes("related")) {
      const sameCategory = ALL_PRODUCTS.filter(
        (p) => p.category === product.category && p.handle !== product.handle,
      );
      add("related", sameCategory, 8);
    }
  }

  if (types.includes("best-sellers")) {
    add("best-sellers", bestSellers(12), 4);
  }
  if (types.includes("new-arrivals")) {
    add("new-arrivals", newArrivals(12), 4);
  }

  return recs;
}

export function getRecommendedProducts(
  recs: ProductRecommendation[],
): Product[] {
  return recs
    .map((r) => productByHandle.get(r.productId))
    .filter((p): p is Product => Boolean(p));
}

/** Given a product, other products in the same looks. */
export function lookMates(productHandle: string): Product[] {
  const mates = new Map<string, number>();
  for (const look of ALL_LOOKS) {
    const handles = look.items.map((i) => i.productHandle);
    if (!handles.includes(productHandle)) continue;
    for (const h of handles) {
      if (h === productHandle) continue;
      mates.set(h, (mates.get(h) ?? 0) + 1);
    }
  }
  return [...mates.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 4)
    .map(([h]) => productByHandle.get(h))
    .filter((p): p is Product => Boolean(p));
}
